server:
  port: 8080

spring:
  application:
    name: school-canteen
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/school_canteen?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
      username: root
      password: root

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id

school-canteen:
  file-path: D:\Developer\IntelliJ IDEA\Project\school-canteen\src\main\resources\static\images\upload\